// Species catalog. Balance numbers mirror the table in CLAUDE.md.
import type { FishVariant, Rng, SpeciesDef, SpeciesId } from './types';

const v = (key: string, name: string, body: string, belly: string, fin: string, accent: string, outline: string): FishVariant => ({
  key,
  name,
  body,
  belly,
  fin,
  accent,
  outline,
});

/** Overlay colors used for any shiny fish, regardless of variant. */
export const SHINY_OUTLINE = '#d9a521';
export const SHINY_SPARKLE = '#fff4c4';

export const SPECIES: Record<SpeciesId, SpeciesDef> = {
  danio: {
    id: 'danio',
    name: 'Zippy Danio',
    unlockLevel: 1,
    cost: { currency: 'shells', amount: 10 },
    growMinutes: 20,
    hungerRate: 2.0,
    sellPrice: 25,
    dropMinutes: 8,
    dropValue: 2,
    speed: 90,
    themeOnly: null,
    traits: ['darts'],
    motion: { waveAmp: 0.65, waveSpeed: 1.6, gait: 'swim' },
    eye: { adult: { x: 0.88, y: 0.52, size: 0.21 }, baby: { x: 0.85, y: 0.55, size: 0.24 } },
    variants: [
      v('zebra', 'Zebra', '#4fa8ff', '#d8f0ff', '#7cc4ff', '#1a3fb8', '#1d4f9e'),
      v('peach', 'Peach', '#ff9a5c', '#ffe0c4', '#ffb87a', '#d4401a', '#a8481c'),
      v('mint', 'Mint', '#3fdc9a', '#d4ffe8', '#7aefc0', '#0f8a5a', '#167a52'),
    ],
  },
  guppy: {
    id: 'guppy',
    name: 'Guppy',
    unlockLevel: 1,
    cost: { currency: 'shells', amount: 15 },
    growMinutes: 25,
    hungerRate: 1.8,
    sellPrice: 35,
    dropMinutes: 8,
    dropValue: 3,
    speed: 60,
    themeOnly: null,
    traits: ['flowyTail'],
    motion: { waveAmp: 1.1, waveSpeed: 1.1, gait: 'swim' },
    eye: { adult: { x: 0.89, y: 0.5, size: 0.13 }, baby: { x: 0.855, y: 0.575, size: 0.17 } },
    variants: [
      v('sunset', 'Sunset', '#ffb02e', '#fff0c4', '#ff5a3d', '#2a6fff', '#b0640a'),
      v('lilac', 'Lilac', '#b07aff', '#efe2ff', '#8a4dff', '#ffd42e', '#6a36b8'),
      v('sky', 'Sky', '#38c8ff', '#dcf6ff', '#1f8cff', '#ffffff', '#1678b0'),
      v('cherry', 'Cherry', '#ff4f7a', '#ffdde6', '#e8204a', '#2a1f4a', '#a81e44'),
    ],
  },
  goldfish: {
    id: 'goldfish',
    name: 'Goldfish',
    unlockLevel: 3,
    cost: { currency: 'shells', amount: 40 },
    growMinutes: 45,
    hungerRate: 1.5,
    sellPrice: 80,
    dropMinutes: 10,
    dropValue: 5,
    speed: 40,
    themeOnly: null,
    traits: ['chubby'],
    motion: { waveAmp: 1, waveSpeed: 0.85, gait: 'swim' },
    eye: { adult: { x: 0.805, y: 0.47, size: 0.19 }, baby: { x: 0.79, y: 0.54, size: 0.2 } },
    variants: [
      v('classic', 'Classic', '#ff8a1a', '#ffe0a0', '#ffb84a', '#e8500a', '#b0500a'),
      v('calico', 'Calico', '#ffd9c4', '#ffffff', '#ffb89a', '#3a4ab8', '#c0704a'),
      v('lemon', 'Lemon', '#ffd21a', '#fff6b0', '#ffe066', '#e89a0a', '#b08a0a'),
    ],
  },
  tetra: {
    id: 'tetra',
    name: 'Neon Tetra',
    unlockLevel: 6,
    cost: { currency: 'shells', amount: 60 },
    growMinutes: 40,
    hungerRate: 1.6,
    sellPrice: 110,
    dropMinutes: 10,
    dropValue: 6,
    speed: 65,
    themeOnly: null,
    traits: ['glowStripe', 'schools'],
    motion: { waveAmp: 0.6, waveSpeed: 1.5, gait: 'swim' },
    eye: { adult: { x: 0.89, y: 0.56, size: 0.18 }, baby: { x: 0.87, y: 0.6, size: 0.25 } },
    variants: [
      v('neon', 'Neon', '#3a8aff', '#e8f4ff', '#ff3a4a', '#2ef0ff', '#1d4fb0'),
      v('cardinal', 'Cardinal', '#ff3a4a', '#ffe0e4', '#ff6a7a', '#2ee0ff', '#a81e2a'),
      v('glowlight', 'Glowlight', '#ffcf8a', '#fff4e0', '#fff0d0', '#ff6a1a', '#c0803a'),
    ],
  },
  betta: {
    id: 'betta',
    name: 'Betta',
    unlockLevel: 5,
    cost: { currency: 'shells', amount: 80 },
    growMinutes: 60,
    hungerRate: 1.2,
    sellPrice: 150,
    dropMinutes: 12,
    dropValue: 8,
    speed: 45,
    themeOnly: null,
    traits: ['bigFins'],
    motion: { waveAmp: 1.6, waveSpeed: 0.6, gait: 'swim' },
    eye: { adult: { x: 0.89, y: 0.54, size: 0.12 }, baby: { x: 0.86, y: 0.52, size: 0.15 } },
    variants: [
      v('royal', 'Royal', '#3a5aff', '#a8c0ff', '#2a4aff', '#8ae0ff', '#1a2aa8'),
      v('ruby', 'Ruby', '#ff2a5a', '#ffa0b8', '#e8104a', '#ffb0c8', '#a0103a'),
      v('opal', 'Opal', '#d8b0ff', '#fff0ff', '#c08aff', '#8ae8ff', '#8a5ac0'),
      v('teal', 'Teal', '#10d0c0', '#a8fff0', '#0ab0a8', '#c4fff0', '#0a7a72'),
    ],
  },
  angelfish: {
    id: 'angelfish',
    name: 'Angelfish',
    unlockLevel: 8,
    cost: { currency: 'shells', amount: 150 },
    growMinutes: 90,
    hungerRate: 1.0,
    sellPrice: 300,
    dropMinutes: 15,
    dropValue: 14,
    speed: 45,
    themeOnly: null,
    traits: ['tall'],
    motion: { waveAmp: 1.25, waveSpeed: 0.6, gait: 'swim' },
    eye: { adult: { x: 0.87, y: 0.47, size: 0.11 }, baby: { x: 0.855, y: 0.53, size: 0.14 } },
    variants: [
      v('silver', 'Silver', '#a8c8f0', '#f4faff', '#c8dcff', '#2a3a6a', '#4a6aa0'),
      v('marble', 'Marble', '#ffe6a8', '#fffbe8', '#fff0c8', '#2a2a4a', '#b09a50'),
      v('blush', 'Gold', '#ffc24a', '#fff0c4', '#ffd88a', '#e86a1a', '#b07a1a'),
    ],
  },
  jellyfish: {
    id: 'jellyfish',
    name: 'Jelly',
    unlockLevel: 10,
    cost: { currency: 'shells', amount: 400 },
    growMinutes: 100,
    hungerRate: 0.9,
    sellPrice: 700,
    dropMinutes: 18,
    dropValue: 25,
    speed: 22,
    themeOnly: null,
    traits: ['jelly'],
    motion: { waveAmp: 1, waveSpeed: 1, gait: 'pulse' },
    eye: { adult: { x: 0.328, y: 0.272, size: 0.1, twinX: 0.657 }, baby: { x: 0.318, y: 0.386, size: 0.15, twinX: 0.677 } },
    bellSplitY: { adult: 0.42, baby: 0.59 },
    // One pink master sprite, recolored per variant by hue rotation (`hue`, degrees).
    variants: [
      { ...v('pink', 'Pink', '#ff8fc4', '#ffe0ef', '#ffb0d6', '#ff4fa3', '#c0306e'), hue: 0 },
      { ...v('sky', 'Sky Blue', '#7cc8ff', '#e0f3ff', '#a8dcff', '#3fa8ff', '#2f78b8'), hue: 232 },
      { ...v('lavender', 'Lavender', '#c4a0ff', '#f0e6ff', '#d8c0ff', '#a070ff', '#7a5ac0'), hue: 285 },
      { ...v('peach', 'Peach', '#ffb08a', '#fff0e4', '#ffc8a8', '#ff7a4a', '#c0603a'), hue: 30 },
      { ...v('mint', 'Mint', '#6ee8b8', '#e0fff2', '#9af0cc', '#2ed8a0', '#2a9a72'), hue: 188 },
    ],
  },
  clownfish: {
    id: 'clownfish',
    name: 'Clownfish',
    unlockLevel: 12,
    cost: { currency: 'shells', amount: 300 },
    growMinutes: 120,
    hungerRate: 1.0,
    sellPrice: 550,
    dropMinutes: 15,
    dropValue: 22,
    speed: 55,
    themeOnly: 'coral',
    traits: [],
    motion: { waveAmp: 0.9, waveSpeed: 1.2, gait: 'swim' },
    eye: { adult: { x: 0.855, y: 0.51, size: 0.19 }, baby: { x: 0.86, y: 0.54, size: 0.21 } },
    variants: [
      v('ocellaris', 'Ocellaris', '#ff7a1a', '#ffb05a', '#ff8a2a', '#ffffff', '#a8400a'),
      v('maroon', 'Maroon', '#d8243a', '#ff6a7a', '#e8344a', '#ffe08a', '#8a1020'),
      v('snowflake', 'Snowflake', '#ff9a2a', '#ffc46a', '#ffaa3a', '#ffffff', '#a85a0a'),
    ],
  },
  puffer: {
    id: 'puffer',
    name: 'Puffy',
    unlockLevel: 15,
    cost: { currency: 'pearls', amount: 5 },
    growMinutes: 180,
    hungerRate: 0.8,
    sellPrice: 900,
    dropMinutes: 20,
    dropValue: 35,
    speed: 35,
    themeOnly: null,
    traits: ['inflates'],
    motion: { waveAmp: 0.12, waveSpeed: 0.8, gait: 'bob' },
    eye: { adult: { x: 0.79, y: 0.375, size: 0.23 }, baby: { x: 0.76, y: 0.44, size: 0.27 } },
    variants: [
      v('sandy', 'Sandy', '#ffd25a', '#fffbe8', '#ffe08a', '#8a6a1a', '#b08a1a'),
      v('spotted', 'Spotted', '#8ad84a', '#f4ffe8', '#b8f07a', '#2a6a1a', '#4a8a1a'),
      v('berry', 'Berry', '#e870d0', '#ffeefb', '#f4a0e4', '#7a1a6a', '#a03a90'),
    ],
  },
  axolotl: {
    id: 'axolotl',
    name: 'Axolotl',
    unlockLevel: 18,
    cost: { currency: 'pearls', amount: 10 },
    growMinutes: 240,
    hungerRate: 0.6,
    sellPrice: 1500,
    dropMinutes: 25,
    dropValue: 50,
    speed: 25,
    themeOnly: null,
    traits: ['walksOnSand', 'smiles'],
    motion: { waveAmp: 0.5, waveSpeed: 0.8, gait: 'walk' },
    eye: { adult: { x: 0.76, y: 0.5, size: 0.21 }, baby: { x: 0.78, y: 0.5, size: 0.24 } },
    variants: [
      v('leucistic', 'Leucistic', '#ffaac4', '#ffe4ee', '#ffc4d8', '#ff2a6a', '#c0607a'),
      v('golden', 'Golden', '#ffd84a', '#fff4c4', '#ffe68a', '#ff6a3a', '#b0901a'),
      v('wild', 'Wild', '#6ab84a', '#c4f08a', '#8ad06a', '#e83a6a', '#3a7a2a'),
      v('lavender', 'Lavender', '#c4a0ff', '#f0e4ff', '#d8c0ff', '#ff4aa0', '#7a5ac0'),
    ],
  },
  koi: {
    id: 'koi',
    name: 'Koi',
    unlockLevel: 20,
    cost: { currency: 'pearls', amount: 15 },
    growMinutes: 300,
    hungerRate: 0.6,
    sellPrice: 2500,
    dropMinutes: 30,
    dropValue: 80,
    speed: 40,
    themeOnly: 'pond',
    traits: [],
    motion: { waveAmp: 1.1, waveSpeed: 0.7, gait: 'swim' },
    eye: { adult: { x: 0.84, y: 0.59, size: 0.14 }, baby: { x: 0.805, y: 0.585, size: 0.17 } },
    variants: [
      v('kohaku', 'Kohaku', '#ffffff', '#ffffff', '#f0f4ff', '#ff3a2a', '#8a8aa8'),
      v('sanke', 'Sanke', '#ffffff', '#ffffff', '#f0f4ff', '#1a1a3a', '#8a8aa8'),
      v('ogon', 'Ogon', '#ffc21a', '#fff0a0', '#ffd84a', '#e8900a', '#b0800a'),
    ],
  },
  cory: {
    id: 'cory',
    special: 'Gobbles pellets that land on the sand before they dissolve',
    name: 'Cory Catfish',
    unlockLevel: 1,
    cost: { currency: 'shells', amount: 20 },
    growMinutes: 25,
    hungerRate: 1.6,
    sellPrice: 40,
    dropMinutes: 9,
    dropValue: 3,
    speed: 35,
    themeOnly: null,
    traits: ['sandDweller', 'smiles'],
    motion: { waveAmp: 0.5, waveSpeed: 1.4, gait: 'swim' },
    eye: { adult: { x: 0.821, y: 0.587, size: 0.17 }, baby: { x: 0.835, y: 0.591, size: 0.155 } },
    variants: [
      v('cream', 'Cream', '#f4e2bc', '#fff8e8', '#e8cfa0', '#6a4020', '#8a6a3a'),

      { ...v('rose', 'Rose', '#f4b8c4', '#fff0f4', '#e898aa', '#7a2a44', '#a8506a'), hue: 330 },
      { ...v('mint', 'Mint', '#b8ecd0', '#f0fff8', '#8ad4b0', '#2a6a4a', '#4a9a78'), hue: 150 },
    ],
  },
  cherry_shrimp: {
    id: 'cherry_shrimp',
    special: 'Nibbles algae: +0.1 cleanliness per minute (counts as half a tank slot)',
    name: 'Cherry Shrimp',
    unlockLevel: 1,
    cost: { currency: 'shells', amount: 12 },
    growMinutes: 15,
    hungerRate: 1.0,
    sellPrice: 20,
    dropMinutes: 10,
    dropValue: 2,
    speed: 28,
    themeOnly: null,
    traits: ['sandDweller', 'halfSlot', 'climbs'],
    motion: { waveAmp: 0.4, waveSpeed: 1.2, gait: 'walk' },
    eye: { adult: { x: 0.756, y: 0.509, size: 0.11 }, baby: { x: 0.699, y: 0.608, size: 0.16 } },
    variants: [
      v('cherry', 'Cherry', '#ff3a4a', '#ffd0d4', '#ff7a84', '#a81a2a', '#a01a2c'),

      { ...v('sunny', 'Sunny', '#ffb02e', '#fff0c4', '#ffd070', '#c46a0a', '#b0700a'), hue: 40 },
      { ...v('blue', 'Blue', '#4a9cff', '#d8ecff', '#8ac0ff', '#1a4ab8', '#1d4f9e'), hue: 225 },
      // Rescue reward (Cherry): deep glossy ruby red.
      { ...v('ruby', 'Ruby', '#d3122e', '#ffd9de', '#f0405a', '#7a0618', '#8a0c20'), hue: 350, rescueOnly: true },
    ],
  },
  kuhli_loach: {
    id: 'kuhli_loach',
    special: 'Burrows into the sand and wiggles back out',
    name: 'Kuhli Loach',
    unlockLevel: 2,
    cost: { currency: 'shells', amount: 25 },
    growMinutes: 30,
    hungerRate: 1.5,
    sellPrice: 50,
    dropMinutes: 9,
    dropValue: 3,
    speed: 30,
    themeOnly: null,
    traits: ['sandDweller', 'burrows'],
    motion: { waveAmp: 1.6, waveSpeed: 0.9, gait: 'swim', fullBody: true },
    eye: { adult: { x: 0.822, y: 0.5, size: 0.32 }, baby: { x: 0.865, y: 0.575, size: 0.24 } },
    variants: [
      v('salmon', 'Salmon', '#ff9a5c', '#ffe0c4', '#ffb87a', '#4a2a14', '#a8481c'),

      { ...v('gold', 'Gold', '#ffd25a', '#fff4c4', '#ffe08a', '#6a4a14', '#b08a1a'), hue: 25 },
      { ...v('rose', 'Rose', '#ff8aa8', '#ffe4ec', '#ffb0c4', '#5a1a30', '#b0405a'), hue: 320 },
      { ...v('shadow_stripe', 'Shadow Stripe', '#3a3a44', '#8a8a96', '#55555f', '#16161c', '#ffb02e'), dark: 0.62, rescueOnly: true },
    ],
  },
  hatchetfish: {
    id: 'hatchetfish',
    special: 'Skims the surface and hops out of the water now and then',
    name: 'Hatchetfish',
    unlockLevel: 3,
    cost: { currency: 'shells', amount: 30 },
    growMinutes: 30,
    hungerRate: 1.7,
    sellPrice: 55,
    dropMinutes: 9,
    dropValue: 4,
    speed: 70,
    themeOnly: null,
    traits: ['surface', 'darts'],
    motion: { waveAmp: 0.5, waveSpeed: 2.0, gait: 'swim' },
    eye: { adult: { x: 0.872, y: 0.42, size: 0.13 }, baby: { x: 0.831, y: 0.451, size: 0.26 } },
    variants: [
      v('silver', 'Silver', '#b8d8ff', '#f0f8ff', '#8ab8f0', '#3a6ab0', '#4a7ab8'),

      { ...v('violet', 'Violet', '#c8b0ff', '#f4eeff', '#a888f0', '#5a3ab0', '#7a5ac0'), hue: 50 },
      { ...v('teal', 'Teal', '#8aece0', '#e8fffb', '#5ad0c4', '#1a7a70', '#2a9a90'), hue: 320 },
      // Rescue reward (Skipper): silver with a soft sky-blue iridescent sheen.
      { ...v('sky_silver', 'Sky Silver', '#d4e4f4', '#ffffff', '#9ad4ff', '#4a7aa8', '#6ab4f0'), hue: 8, rescueOnly: true },
    ],
  },
  crab: {
    id: 'crab',
    special: 'Digs up 1–2 bonus shells every ~15 minutes',
    name: 'Crab',
    unlockLevel: 2,
    cost: { currency: 'shells', amount: 35 },
    growMinutes: 40,
    hungerRate: 1.3,
    sellPrice: 70,
    dropMinutes: 10,
    dropValue: 4,
    speed: 24,
    themeOnly: null,
    traits: ['sandDweller', 'sideways', 'climbs'],
    motion: { waveAmp: 0.05, waveSpeed: 1.0, gait: 'walk' },
    eye: { adult: { x: 0.39, y: 0.26, size: 0.17, twinX: 0.61 }, baby: { x: 0.37, y: 0.27, size: 0.24, twinX: 0.64 } },
    variants: [
      v('red', 'Red', '#ff5a3a', '#ffd4c4', '#ff8a6a', '#a8200a', '#a8301a'),

      { ...v('orange', 'Orange', '#ff9a3a', '#ffe0b8', '#ffba6a', '#b05a0a', '#b0600a'), hue: 35 },
      { ...v('violet', 'Violet', '#b07aff', '#efe2ff', '#c8a4ff', '#5a2ab0', '#6a36b8'), hue: 270 },
      // Rescue reward (Pinch): deep coral-red, pearly belly.
      { ...v('stormshell', 'Stormshell', '#d8203c', '#fff0f4', '#f0506a', '#8a0c28', '#8a1230'), hue: 345, rescueOnly: true },
    ],
  },
};

/** Species in table order (by shop listing). */
export const SPECIES_LIST: SpeciesDef[] = Object.values(SPECIES).sort((a, b) => a.unlockLevel - b.unlockLevel);

export function getSpecies(id: SpeciesId): SpeciesDef {
  return SPECIES[id];
}

/** How many tank slots one of this species takes (cherry shrimp: half a slot). */
export function slotWeight(id: SpeciesId): number {
  return SPECIES[id].traits.includes('halfSlot') ? 0.5 : 1;
}

export function getVariant(speciesId: SpeciesId, variantKey: string): FishVariant {
  const species = SPECIES[speciesId];
  return species.variants.find((variant) => variant.key === variantKey) ?? species.variants[0]!;
}

export function randomVariantKey(speciesId: SpeciesId, rng: Rng): string {
  const variants = SPECIES[speciesId].variants.filter((x) => !x.rescueOnly);
  return variants[Math.floor(rng() * variants.length)]!.key;
}
