// Original audio for the trailer, synthesized from scratch (so there are no licensing questions): a cozy lo-fi loop and the SFX.
//   npx tsx scripts/trailer/audio.ts [outDir]     -> <outDir>/music.wav, <outDir>/sfx/<name>.wav
// Everything here is generated by this script and released as CC0 (public domain dedication).
import fs from 'node:fs';
import path from 'node:path';

const SR = 44100;
const OUT = path.resolve(process.argv[2] ?? 'trailer/audio');

function rngFactory(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rnd = rngFactory(7);

function writeWav(file: string, left: Float32Array, right: Float32Array): void {
  const n = left.length;
  const buf = Buffer.alloc(44 + n * 4);
  buf.write('RIFF', 0);
  buf.writeUInt32LE(36 + n * 4, 4);
  buf.write('WAVEfmt ', 8);
  buf.writeUInt32LE(16, 16);
  buf.writeUInt16LE(1, 20);
  buf.writeUInt16LE(2, 22);
  buf.writeUInt32LE(SR, 24);
  buf.writeUInt32LE(SR * 4, 28);
  buf.writeUInt16LE(4, 32);
  buf.writeUInt16LE(16, 34);
  buf.write('data', 36);
  buf.writeUInt32LE(n * 4, 40);
  for (let i = 0; i < n; i++) {
    buf.writeInt16LE(Math.round(Math.max(-1, Math.min(1, left[i]!)) * 32767), 44 + i * 4);
    buf.writeInt16LE(Math.round(Math.max(-1, Math.min(1, right[i]!)) * 32767), 46 + i * 4);
  }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, buf);
}

const midi = (n: number) => 440 * Math.pow(2, (n - 69) / 12);
const TAU = Math.PI * 2;

/** Mono scratch buffer helpers. */
class Track {
  readonly d: Float32Array;
  constructor(seconds: number) {
    this.d = new Float32Array(Math.ceil(seconds * SR));
  }
  add(at: number, fn: (t: number) => number, dur: number, gain = 1): void {
    const s = Math.floor(at * SR);
    const n = Math.floor(dur * SR);
    for (let i = 0; i < n && s + i < this.d.length; i++) this.d[s + i]! += fn(i / SR) * gain;
  }
}

function lowpass(x: Float32Array, cutoff: number): Float32Array {
  const a = 1 - Math.exp((-TAU * cutoff) / SR);
  let y = 0;
  const out = new Float32Array(x.length);
  for (let i = 0; i < x.length; i++) {
    y += a * (x[i]! - y);
    out[i] = y;
  }
  return out;
}
function highpass(x: Float32Array, cutoff: number): Float32Array {
  const lp = lowpass(x, cutoff);
  const out = new Float32Array(x.length);
  for (let i = 0; i < x.length; i++) out[i] = x[i]! - lp[i]!;
  return out;
}

// ------------------------------------------------------------------ music
function music(seconds: number): { l: Float32Array; r: Float32Array } {
  const bpm = 76;
  const beat = 60 / bpm;
  const bar = beat * 4;
  const swing = 0.16 * beat; // lazy swing on off-beat eighths
  // I – vi – IV – V6 in C, voiced low and warm (midi numbers)
  const chords = [
    { root: 36, notes: [55, 59, 62, 64] }, // Cmaj7 (G B D E)
    { root: 33, notes: [55, 60, 64, 67] }, // Am7 (G C E ... ) rounded
    { root: 41, notes: [53, 57, 60, 64] }, // Fmaj7
    { root: 43, notes: [55, 59, 62, 64] }, // G6
  ];
  const keys = new Track(seconds);
  const bass = new Track(seconds);
  const drums = new Track(seconds);
  const mel = new Track(seconds);
  const bars = Math.ceil(seconds / bar);

  const rhodes = (f: number, vel: number) => (t: number) => {
    const env = Math.exp(-t * 2.4) * Math.min(1, t * 160);
    const bell = Math.exp(-t * 9);
    return (
      env * (Math.sin(TAU * f * t) * 0.6 + Math.sin(TAU * f * 2 * t) * 0.16 + Math.sin(TAU * f * 3.01 * t) * 0.05) * vel +
      bell * Math.sin(TAU * f * 5.9 * t) * 0.05 * vel
    );
  };
  for (let b = 0; b < bars; b++) {
    const t0 = b * bar;
    const ch = chords[b % 4]!;
    // chord stabs on 1 and 2.5 (strummed)
    [0, 2.5].forEach((pos, pi) => {
      ch.notes.forEach((n, i) => {
        keys.add(t0 + pos * beat + i * 0.022 + (pos > 0 ? swing : 0), rhodes(midi(n), pi ? 0.1 : 0.14), 2.2, 1);
      });
    });
    // bass: root on 1, fifth-ish pickup on 3.5
    bass.add(t0, (t) => Math.sin(TAU * midi(ch.root) * t) * Math.exp(-t * 2.2) * 0.5 * Math.min(1, t * 120), 1.4);
    bass.add(t0 + 2 * beat + swing, (t) => Math.sin(TAU * midi(ch.root) * t) * Math.exp(-t * 3) * 0.32 * Math.min(1, t * 120), 0.9);
    bass.add(t0 + 3.5 * beat, (t) => Math.sin(TAU * midi(ch.root + 7) * t) * Math.exp(-t * 4) * 0.22 * Math.min(1, t * 120), 0.6);
    // drums: soft kick 1 & 2.75, snare 2 & 4, hats on eighths
    for (const k of [0, 2.75]) {
      drums.add(t0 + k * beat, (t) => Math.sin(TAU * (48 + 90 * Math.exp(-t * 28)) * t) * Math.exp(-t * 9) * 0.65, 0.4);
    }
    for (const sn of [1, 3]) {
      drums.add(t0 + sn * beat, (t) => (rnd() * 2 - 1) * Math.exp(-t * 20) * 0.22 + Math.sin(TAU * 185 * t) * Math.exp(-t * 18) * 0.18, 0.28);
    }
    for (let h = 0; h < 8; h++) {
      const at = t0 + h * 0.5 * beat + (h % 2 ? swing : 0);
      const vel = h % 2 ? 0.07 : 0.1;
      drums.add(at, (t) => (rnd() * 2 - 1) * Math.exp(-t * 90) * vel, 0.07);
    }
    // sparse pentatonic melody (C D E G A), one phrase every two bars
    if (b % 2 === 1 && b > 0) {
      const phrase = [[72, 0], [76, 1], [74, 1.75], [72, 2.5], [69, 3.25]] as const;
      phrase.forEach(([n, p], i) => {
        const note = n + (b % 4 === 3 && i > 2 ? 3 : 0);
        mel.add(t0 + p * beat + (i % 2 ? swing * 0.5 : 0), (t) => (Math.sin(TAU * midi(note) * t) * 0.5 + Math.sin(TAU * midi(note) * 2 * t) * 0.08) * Math.exp(-t * 3.4) * Math.min(1, t * 90) * 0.1, 1.2);
      });
    }
  }
  // gentle delay on the melody + keys
  const send = new Float32Array(keys.d.length);
  for (let i = 0; i < send.length; i++) send[i] = keys.d[i]! * 0.6 + mel.d[i]!;
  const dl = Math.floor(beat * 0.75 * SR);
  const wet = new Float32Array(send.length);
  for (let i = dl; i < send.length; i++) wet[i] = send[i - dl]! * 0.34 + wet[i - dl]! * 0.34;
  const wetL = lowpass(wet, 2600);

  const l = new Float32Array(keys.d.length);
  const r = new Float32Array(keys.d.length);
  const lpKeys = lowpass(keys.d, 3200);
  const lpDrums = lowpass(drums.d, 7000);
  // vinyl crackle + warm hiss
  const crackle = new Float32Array(l.length);
  for (let i = 0; i < crackle.length; i++) {
    if (rnd() < 0.00035) crackle[i] = (rnd() * 2 - 1) * 0.12;
    crackle[i] += (rnd() * 2 - 1) * 0.004;
  }
  const crk = highpass(lowpass(crackle, 6000), 400);
  for (let i = 0; i < l.length; i++) {
    const wow = 1; // (pitch wobble is baked into notes via the slight detune of the strum)
    const m = (lpKeys[i]! + mel.d[i]! + wetL[i]!) * wow;
    l[i] = m * 0.9 + bass.d[i]! + lpDrums[i]! * 0.8 + crk[i]!;
    r[i] = m * 1.0 + bass.d[i]! + lpDrums[i]! * 0.9 + crk[i]! * 0.8;
  }
  // soft limiter
  for (let i = 0; i < l.length; i++) {
    l[i] = Math.tanh(l[i]! * 1.2) * 0.7;
    r[i] = Math.tanh(r[i]! * 1.2) * 0.7;
  }
  return { l, r };
}

// ------------------------------------------------------------------ sfx
const sfx: Record<string, { dur: number; make: (tr: Track) => void }> = {
  plop: {
    dur: 0.35,
    make: (tr) => {
      tr.add(0, (t) => Math.sin(TAU * (520 * Math.exp(-t * 14) + 190) * t) * Math.exp(-t * 16) * 0.8, 0.3);
      tr.add(0, (t) => (rnd() * 2 - 1) * Math.exp(-t * 60) * 0.12, 0.08);
    },
  },
  coin: {
    dur: 0.5,
    make: (tr) => {
      tr.add(0, (t) => Math.sin(TAU * 1319 * t) * Math.exp(-t * 14) * 0.55, 0.3);
      tr.add(0.07, (t) => (Math.sin(TAU * 1760 * t) + Math.sin(TAU * 3520 * t) * 0.15) * Math.exp(-t * 9) * 0.5, 0.45);
    },
  },
  chime: {
    dur: 1.6,
    make: (tr) => {
      [1046.5, 1318.5, 1568, 2093].forEach((f, i) =>
        tr.add(i * 0.085, (t) => (Math.sin(TAU * f * t) + Math.sin(TAU * f * 2.76 * t) * 0.18) * Math.exp(-t * 3.2) * 0.34, 1.4),
      );
    },
  },
  crack: {
    dur: 0.5,
    make: (tr) => {
      [0, 0.07, 0.15].forEach((o, i) => tr.add(o, (t) => (rnd() * 2 - 1) * Math.exp(-t * 140) * (0.5 - i * 0.1), 0.06));
      tr.add(0.2, (t) => Math.sin(TAU * 140 * t) * Math.exp(-t * 20) * 0.35, 0.25);
    },
  },
  pop: {
    dur: 0.25,
    make: (tr) => tr.add(0, (t) => Math.sin(TAU * (380 + 700 * (1 - Math.exp(-t * 40))) * t) * Math.exp(-t * 26) * 0.6, 0.2),
  },
  whoosh: {
    dur: 0.8,
    make: (tr) => {
      const n = new Float32Array(Math.floor(0.8 * SR));
      for (let i = 0; i < n.length; i++) n[i] = rnd() * 2 - 1;
      const f = highpass(lowpass(n, 2400), 500);
      for (let i = 0; i < n.length; i++) {
        const t = i / SR;
        tr.d[i] += f[i]! * Math.sin(Math.PI * Math.min(1, t / 0.8)) ** 2 * 0.5;
      }
    },
  },
  sparkle: {
    dur: 1.0,
    make: (tr) => {
      for (let i = 0; i < 9; i++) {
        const f = 2200 + rnd() * 2600;
        tr.add(i * 0.05 + rnd() * 0.02, (t) => Math.sin(TAU * f * t) * Math.exp(-t * 18) * 0.18, 0.25);
      }
    },
  },
};

function main(): void {
  fs.mkdirSync(path.join(OUT, 'sfx'), { recursive: true });
  const m = music(36);
  writeWav(path.join(OUT, 'music.wav'), m.l, m.r);
  for (const [name, def] of Object.entries(sfx)) {
    const tr = new Track(def.dur);
    def.make(tr);
    const d = tr.d.map((v) => Math.tanh(v * 1.1) * 0.8);
    writeWav(path.join(OUT, 'sfx', `${name}.wav`), d, d);
  }
  console.log(`audio written to ${OUT}`);
}
main();
